package com.lintsec.scanner;

public enum PayloadId {
    XSS_CANARY_PLAIN,
    XSS_CANARY_REFLECTED,
    SQLI_SINGLE_QUOTE,
    SQLI_BALANCED,
    OPEN_REDIRECT_ABSOLUTE,
    PATH_TRAVERSAL_UNIX,
    PATH_TRAVERSAL_WINDOWS,
    CMDI_UNIX_ID,
    CMDI_WINDOWS_VER
}
